const products = [
  {
    "id": "glasses_0",
    "name": "Burnikk",
    "brand": "Sexbomb",
    "price": 240.00,
    "quantity": 10,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_0.png", "glass_2.png", "glass_5.png"],
    "sizes": [
      28,
      36,
      42
    ],
    "image": "glass_0.png",
    "imageUrl": "glass_0.png",
    "isFeatured": true,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_1",
    "name": "Kibal Batal",
    "brand": "Kibal Black",
    "price": 674.00,
    "quantity": 11,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_1.png", "glass_12.png", "glass_5.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_1.png",
    "imageUrl": "glass_1.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_2",
    "name": "Tiktilaok Manok",
    "brand": "Sexbomb",
    "price": 78.99,
    "quantity": 12,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
     "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_2.png", "glass_4.png", "glass_6.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_2.png",
    "imageUrl": "glass_2.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_3",
    "name": "Very Nice",
    "brand": "Salt Maalat",
    "price": 450.99,
    "quantity": 13,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_3.png", "glass_8.png", "glass_10.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_3.png",
    "imageUrl": "glass_3.png",
    "isFeatured": false,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_4",
    "name": "Quake Overload",
    "brand": "Salt",
    "price": 365.99,
    "quantity": 14,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_4.png", "glass_8.png", "glass_6.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_4.png",
    "imageUrl": "glass_4.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_5",
    "name": "Kutu",
    "brand": "Sexbomb",
    "price": 340.99,
    "quantity": 15,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_5.png", "glass_11.png", "glass_17.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_5.png",
    "imageUrl": "glass_5.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "Tuluk",
    "name": "Black Kibal",
    "brand": "Brand B",
    "price": 56.00,
    "quantity": 16,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_6.png", "glass_9.png", "glass_8.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_6.png",
    "imageUrl": "glass_6.png",
    "isFeatured": true,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_7",
    "name": "Takla Green",
    "brand": "Sexbomb",
    "price": 106.99,
    "quantity": 17,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_7.png", "glass_11.png", "glass_12.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_7.png",
    "imageUrl": "glass_7.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_8",
    "name": "Balakubak",
    "brand": "Betsin Maalat",
    "price": 259.99,
    "quantity": 18,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_8.png", "glass_11.png", "glass_12.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_8.png",
    "imageUrl": "glass_8.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_9",
    "name": "Pitaklan",
    "brand": "Black Kibal",
    "price": 344.99,
    "quantity": 19,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_9.png", "glass_11.png", "glass_12.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_9.png",
    "imageUrl": "glass_9.png",
    "isFeatured": false,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_10",
    "name": "Burnikk",
    "brand": "Sexbomb",
    "price": 250.99,
    "quantity": 20,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_10.png", "glass_11.png", "glass_12.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_10.png",
    "imageUrl": "glass_10.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_11",
    "name": "Sipon Malapot",
    "brand": "Salt",
    "price": 110.99,
    "quantity": 21,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_11.png", "glass_13.png", "glass_12.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_11.png",
    "imageUrl": "glass_11.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_12",
    "name": "Buldit",
    "brand": "Salt Maalat",
    "price": 141.99,
    "quantity": 22,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_12.png", "glass_13.png", "glass_14.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_12.png",
    "imageUrl": "glass_12.png",
    "isFeatured": true,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_13",
    "name": "Merry Christmas",
    "brand": "Salt Maalat",
    "price": 79.99,
    "quantity": 23,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_13.png", "glass_11.png", "glass_15.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_13.png",
    "imageUrl": "glass_13.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_14",
    "name": "Tilis Malaput",
    "brand": "Betsin Maalat",
    "price": 67.99,
    "quantity": 24,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_14.png", "glass_15.png", "glass_13.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_14.png",
    "imageUrl": "glass_14.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_15",
    "name": "Murry",
    "brand": "Salt Maalat",
    "price": 129.99,
    "quantity": 25,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_15.png", "glass_14.png", "glass_13.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_15.png",
    "imageUrl": "glass_15.png",
    "isFeatured": false,
    "isRecommended": true,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_16",
    "name": "Tilapia",
    "brand": "Salt Maalat",
    "price": 115.99,
    "quantity": 26,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "fashion",
      "comfortable",
      "stylish",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "fashion-forward",
      "brown",
      "black",
      "gold",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_16.png", "glass_14.png", "glass_13.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_16.png",
    "imageUrl": "glass_16.png",
    "isFeatured": true,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
  {
    "id": "glasses_17",
    "name": "Kibal Batal",
    "brand": "Kibal Black",
    "price": 450.99,
    "quantity": 27,
    "maxQuantity": 20,
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.",
    "keywords": [
      "eyewear",
      "glasses",
      "cute",
      "black",
      "gold",
      "vintage",
      "sporty",
      "geek-chic",
      "oversized",
      "round",
      "aviator",
      "fashion",
      "comfortable",
      "trendy",
      "modern",
      "fashionable",
      "chic",
      "unique",
      "stylish",
      "brown",
    ],
    "selectedSize": "M",
    "selectedColor": "Black",
    "imageCollection": ["glass_17.png", "glass_14.png", "glass_13.png"],
    "sizes": [
      38,
      40,
      42
    ],
    "image": "glass_17.png",
    "imageUrl": "glass_17.png",
    "isFeatured": false,
    "isRecommended": false,
    "availableColors": [
      "Black",
      "Brown",
      "Gold",
      "rgb(32, 65, 197)",
      "rgb(197, 0, 197)",
      "rgb(132, 3, 9)",
      "rgb(0, 77, 132)",
      "rgb(117, 54, 0)",
      "rgb(0, 240, 224)",
      "rgb(19, 247, 2)",
    ]
  },
 
];

export default products;
